# Generated by Django 3.2.6 on 2021-08-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0002_auto_20210827_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webtoon',
            name='image',
        ),
    ]
