# Generated by Django 3.2.6 on 2021-08-29 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0005_alter_webtoon_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=300, null=True)),
                ('make_date', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webtoon.mcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtoon.webtoon')),
            ],
        ),
    ]
