# Generated by Django 3.2.6 on 2021-09-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0008_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoon',
            name='user_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
